project/models.py
# ================================================
# @type Import
# @name db, ma
# @desc db database, ma marshmallow objects
# ================================================
from project import db

# ================================================
# @type     Class
# @name     User
# @params   {string} first name, 
#           {string} last name, 
#           {string} email, 
#           {string} details
# @desc     User model class
# ================================================
class User (db.Model):
    __tablename__   = 'user'
    id              = db.Column(db.Integer, primary_key=True)
    first_name      = db.Column(db.String(62))
    last_name       = db.Column(db.String(62))
    email           = db.Column(db.String(62), unique=True)
    details         = db.Column(db.Text)
    type            = db.Column(db.String(16), nullable=True)
    password        = db.Column(db.String(255), nullable=True)
    
    def __init__(self, first_name, last_name, email, details):
        self.first_name = first_name
        self.last_name  = last_name
        self.email      = email
        self.details    = details

project/login/forms.py
# ================================================================================
# @type Import
# @name Form, StringField, TextAreaField, PasswordField, validators, SelectField
# @desc Include some of wtforms clases which used for our input field.
# =================================================================================
from wtforms import Form, StringField, PasswordField, validators
from wtforms.fields.html5 import EmailField

# ================================================
# @type Class
# @name UserAddForm
# @params Form Object
# @desc UserAddForm is a class from forms file.
#       This class use for make our input fields
#       and field rules.
# ================================================
class LoginForm(Form):
    email      = EmailField('Email', [validators.DataRequired(), validators.Email()],  render_kw={"placeholder":"Email"})
    password   = PasswordField('Password', [validators.Length(max=1000, min=4)], render_kw={"placeholder":"Login Password"})

project/users/forms.py
# ================================================================================
# @type Import
# @name Form, StringField, TextAreaField, PasswordField, validators, SelectField
# @desc Include some of wtforms clases which used for our input field.
# =================================================================================
from wtforms import Form, StringField, TextAreaField, PasswordField, validators, SelectField
from wtforms.fields.html5 import EmailField

# ================================================
# @type Class
# @name UserAddForm
# @params Form Object
# @desc UserAddForm is a class from forms file.
#       This class use for make our input fields
#       and field rules.
# ================================================
class UserAddForm(Form):
    first_name = StringField('First Name', [validators.Length(min=1,max=50)],  render_kw={"placeholder":"First Name"} )
    last_name  = StringField('Last Name', [validators.Length(min=4, max=50)],  render_kw={"placeholder":"Last Name"} )
    email      = EmailField('Email', [validators.DataRequired(), validators.Email()],  render_kw={"placeholder":"Email"})
    # status     = SelectField('Set Status', choices=[('0','Inactive'),('1','Active')])
    details    = StringField('Details', [validators.Length(max=1000)], render_kw={"placeholder":"User Bio Details"})

project/__init__.py
# ===========================================================
# @type Import
# @name 
# @desc flask_sqlalchemy use for SQL ORM. 
#       flask_marshmallow use for filtering our db table column.
#       flask_modus use for 
# ===========================================================
from flask import Flask, jsonify, render_template, request
from flask_sqlalchemy import SQLAlchemy
from flask_marshmallow import Marshmallow
# from flask_modus import Modus
from flask_migrate import Migrate

# ===========================================================
# @type Initialize
# @name app
# @desc initialize our flask application to the app variable.
# ===========================================================
app = Flask(__name__)

# ===========================================================
# @type Initialize
# @name ma
# @desc initialize Marshmallow module.
# ===========================================================
ma  = Marshmallow(app)

# ===========================================================
# @type Initialize
# @name modus
# @desc initialize flask_modus module. 
# ===========================================================
# modus = Modus(app)

# ================================================
# @type Assign
# @name app.config['SQLALCHEMY_DATABASE_URI']
# @desc MySql connection. 
# ================================================
app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://root:''@localhost/flask_sqlalchemy'
# Give us SQL Query warning. 
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
# set secret key
app.config['SECRET_KEY'] = "secret123456"
app.config['TESTING'] = True

# =================================================
# @type variable
# @name db
# @desc SQLalchemy object assign to the db variable.
#===================================================
db = SQLAlchemy(app)

# migrate = Migrate(app, db)

# Import Blueprint views
from project.login.views import login_blueprint
from project.users.views import users_blueprint
from project.messages.views import messages_blueprint


# Register my Blueprint
app.register_blueprint(login_blueprint, url_prefix='/login')
app.register_blueprint(users_blueprint, url_prefix='/users')
app.register_blueprint(messages_blueprint, url_prefix='/messages')

@app.route('/')
def root():
    data = 'Text form __init__ !!!'
    return data

project/login/views.py
# =============================================================================
# @type Import
# @name redirect, Blueprint, render_template, request, url_for, jsonify, flash
# @desc include class, method and defination form flask module
# ==============================================================================
from flask import redirect, Blueprint, render_template, request, url_for, jsonify, flash, session

from project.services.authentication.UsserLogged import login_required
# ================================================
# @type Import
# @name UserAddForm
# @desc UserAddForm is a class from forms file
# ================================================
from project.login.forms import LoginForm

# ================================================
# @type Import
# @name db, ma
# @desc db database, ma marshmallow objects
# ================================================
from project import db, ma


# ================================================
# @type Import
# @name User
# @desc import User model class.
# ================================================
from project.users.views import User

# ================================================
# @type Init
# @name users_blueprint
# @desc init bludeprint class and pass 3 argument like, folder name, templat folder name
# ================================================
login_blueprint = Blueprint('login', __name__, template_folder='templates')


@login_blueprint.route('/', methods=['GET', 'POST'])
def index():
    # pass request data to the form class
    form = LoginForm(request.form)
    error = ''
    data  = { 'loged_in': False }
    try: 
        # user make a login request.
        if request.method == "POST" and form.validate():
            # get user data using email and password. 
            user_data = User.query.filter_by(email=form.email.data, password=form.password.data).first()
            # if user are exists in database
            if hasattr(user_data, 'id') :
                flash("You are logged in.")
                session['logged_id']  = True
                # session['login_info'] = user_data    
                return redirect( url_for('users.index') )
                
            else:
                flash("Invalid email or password. Try again.", "danger")
    except Exception as e:
        flash("Unable to find account", "danger")
    return render_template("login/index.html", data=data, error=error, form=form)



@login_blueprint.route("/logout")
@login_required
def logout():
    session.clear()
    flash("You have been logged out!", "success")
    return redirect(url_for('login.index'))

project/messages/views.py
from flask import redirect, url_for, render_template, Blueprint

messages_blueprint = Blueprint('messages', __name__, template_folder='templates')

@messages_blueprint.route('/')
def index():
    return render_template('messages/index.html')

project/users/views.py
# =============================================================================
# @type Import
# @name redirect, Blueprint, render_template, request, url_for, jsonify, flash
# @desc include class, method and defination form flask module
# ==============================================================================
from flask import redirect, Blueprint, render_template, request, url_for, jsonify, flash, session

from project.services.authentication.UsserLogged import login_required
# ================================================
# @type Import
# @name UserAddForm
# @desc UserAddForm is a class from forms file
# ================================================
from project.users.forms import UserAddForm

#from project.models import User

# ================================================
# @type Import
# @name db, ma
# @desc db database, ma marshmallow objects
# ================================================
from project import db, ma

# ================================================
# @type Init
# @name users_blueprint
# @desc init bludeprint class and pass 3 argument like, folder name, templat folder name
# ================================================
users_blueprint = Blueprint('users', __name__, template_folder='templates')

from project.models import User
# Define user model class
# class User (db.Model):
#     __tablename__   = 'user'
#     id              = db.Column(db.Integer, primary_key=True)
#     first_name      = db.Column(db.String(62))
#     last_name       = db.Column(db.String(62))
#     email           = db.Column(db.String(62), unique=True)
#     details         = db.Column(db.Text)
#     type            = db.Column(db.String(16), nullable=True)
#     password        = db.Column(db.String(255), nullable=True)
    
#     def __init__(self, first_name, last_name, email, details):
#         self.first_name = first_name
#         self.last_name  = last_name
#         self.email      = email
#         self.details    = details

# =============================================== 
# User Schema
# @desc 
# ===============================================
# class UserSchema(ma.Schema):
#     class Meta:
#         # Fields to expose
#         fields = ("id", "first_name", "last_name", "email", "details")
        
# Init DB schema
# user_schema  = UserSchema(strict=True)
# users_schema = UserSchema(many=True, strict=True)       

# =============================================== 
# @type Routes
# @request_url  http://localhost:5000/users/
# @request_type GET, POST
# @desc 
# ===============================================
@users_blueprint.route('/', methods=["GET","POST"])
@login_required
def index():
    data = { 'loged_in': True }
    return render_template('users/index.html', data=data, example=User.query.all() )


# =============================================== 
# @type Routes
# @request_url  http://localhost:5000/users/add
# @request_type POST
# @desc using json add an user to the db. 
# ===============================================
@users_blueprint.route('/add', methods=["post"])
@login_required
def add_user():
    first_name = request.json['first_name']
    last_name  = request.json['last_name']
    email      = request.json['email']
    details    = request.json['details']
    
    new_user = User(first_name, last_name, email, details)
    db.session.add(new_user)
    db.session.commit()
    return user_schema.jsonify(new_user)


# =============================================== 
# @type Routes
# @request_url  users/details/<int:id>
# @request_type GET
# @desc 
# ===============================================
@users_blueprint.route('/details/<int:id>')
@login_required
def view_user(id):
    user_all_data = User.query.get(id)
    data = { 'loged_in': True }
    return render_template('users/user_details.html', data=data, user=user_all_data)


# =============================================== 
# @type Routes
# @request_url  users/edit/<int:id>
# @request_type GET
# @desc 
# ===============================================
@users_blueprint.route('/edit/<int:id>')
@login_required
def edit_user(id):
    user_data = User.query.get(id)
    data = { 'loged_in': True }
    return render_template('users/edit_details.html', data=data, user_data=user_data)


# =============================================== 
# @type Routes
# @request_url  users/addnewuser/<int:id>
# @request_type POST, GET
# @desc 
# ===============================================
@users_blueprint.route('/addnewuser', methods=['POST','GET'])
@login_required
def addnewuser():
    # pass request data to the form class
    form = UserAddForm(request.form)
    
    # save form data to the database if its a post request
    if request.method == 'POST' and form.validate():
        first_name = form.first_name.data
        last_name  = form.last_name.data
        email      = form.email.data
        detials    = form.details.data
        
        add_new = User(first_name, last_name, email, detials)
        db.session.add(add_new)
        db.session.commit()
        
        flash('New user add successfully.', 'success')
        redirect( url_for('users.addnewuser') )
                          
    data = { 'loged_in': True }                
    # render page if its a get request
    return render_template('users/add_user.html',data=data, form=form)


# =============================================== 
# @type Routes
# @request_url  users/edituser/<int:id>
# @request_type  GET
# @desc edit an user using its given id. 
# ===============================================  
@users_blueprint.route('/edituser/<int:id>', methods=['POST','GET'])
@login_required
def edituser(id):
    # set form type.
    add_user  = False
    
    # get user data by given user id. 
    user_data = User.query.filter_by(id=id).first()
    
    # pass request data to the form class
    form = UserAddForm(request.form)
    
    if request.method == 'POST' and form.validate():
        user_data.first_name = request.form.get("first_name")
        user_data.last_name = request.form.get("last_name")
        user_data.email = request.form.get("email")
        user_data.details = request.form.get("details")
        db.session.commit()
        # Set flash success message.
        flash('User data update successfully', 'success')
        # redirect_url is positional argument
        # id is keyword arguments need to pass.
        return redirect(url_for('users.edituser', id=user_data.id))
    
    form.first_name.data = user_data.first_name
    form.last_name.data = user_data.last_name
    form.email.data = user_data.email
    form.details.data = user_data.details
    
    data = { 'loged_in': True }
    return render_template('users/add_user.html', 
                           data=data,
                           action="Edit", 
                           add_user = add_user, 
                           form=form)
    
 
# =============================================== 
# @type Routes
# @request_url  users/deleteuser/<int:id>
# @request_type  GET
# @desc delete an user using its given id. 
# ===============================================   
@users_blueprint.route('/deleteuser/<int:id>', methods=['GET'])
def deleteuser(id):
    try:
        user = User.query.filter_by(id=id).first()
        db.session.delete(user)
        db.session.commit()
    except Exception as e:
        print("Failed to add book")
        print(e)
    data = { 'loged_in': True }
    return redirect( url_for('users.index'), data=data )

project/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>
        {% block title %} {% endblock %}
  </title>

  <!-- Custom fonts for this template-->
  <link href="{{ url_for('static', filename='vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{{ url_for('static', filename='css/sb-admin-2.min.css') }}" rel="stylesheet">

</head>

<body id="page-top">
    {% if data.loged_in: %}
        <!-- Page Wrapper -->
        <div id="wrapper">
            
            <!-- Sidebar -->
            {% include 'sidebar.html' %}
            <!-- End of Sidebar -->
            
            <!-- Content Wrapper -->
            <div id="content-wrapper" class="d-flex flex-column">
        
            <!-- Main Content -->
            <div id="content">
        
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
        
                <!-- Sidebar Toggle (Topbar) -->
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>
        
                
                <!-- Topbar Navbar -->
                <ul class="navbar-nav ml-auto">
        
                    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                    <li class="nav-item dropdown no-arrow d-sm-none">
                    <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-search fa-fw"></i>
                    </a>
                    <!-- Dropdown - Messages -->
                    <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                        <form class="form-inline mr-auto w-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                            </div>
                        </div>
                        </form>
                    </div>
                    </li>
        
                    <!-- Nav Item - Alerts -->
                    <li class="nav-item dropdown no-arrow mx-1">
                    <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-bell fa-fw"></i>
                        <!-- Counter - Alerts -->
                        <span class="badge badge-danger badge-counter">3+</span>
                    </a>
                    <!-- Dropdown - Alerts -->
                    <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                        <h6 class="dropdown-header">
                        Alerts Center
                        </h6>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="mr-3">
                                <div class="icon-circle bg-primary">
                                <i class="fas fa-file-alt text-white"></i>
                                </div>
                            </div>
                            <div>
                                <div class="small text-gray-500">December 12, 2019</div>
                                <span class="font-weight-bold">A new monthly report is ready to download!</span>
                            </div>
                        </a>
                        <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
                    </div>
                    </li>
        
                    <!-- Nav Item - Messages -->
                    <li class="nav-item dropdown no-arrow mx-1">
                    <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-envelope fa-fw"></i>
                        <!-- Counter - Messages -->
                        <span class="badge badge-danger badge-counter">7</span>
                    </a>
                    <!-- Dropdown - Messages -->
                    <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
                        <h6 class="dropdown-header">
                        Message Center
                        </h6>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                        <div class="dropdown-list-image mr-3">
                            <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
                            <div class="status-indicator bg-success"></div>
                        </div>
                        <div class="font-weight-bold">
                            <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
                            <div class="small text-gray-500">Emily Fowler · 58m</div>
                        </div>
                        </a>
                        <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
                    </div>
                    </li>
        
                    <div class="topbar-divider d-none d-sm-block"></div>
        
                    <!-- Nav Item - User Information -->
                    <li class="nav-item dropdown no-arrow">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="mr-2 d-none d-lg-inline text-gray-600 small">Muhammad Hasan</span>
                        <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
                    </a>
                    <!-- Dropdown - User Information -->
                    <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="#">
                        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                        Profile
                        </a>
                        <a class="dropdown-item" href="#">
                        <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                        Settings
                        </a>

                        <a class="dropdown-item" href="#">
                            <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                            Activity Log
                        </a>
                        <div class="dropdown-divider"></div>

                        <a  class="dropdown-item" 
                            href="" 
                            data-toggle="modal" 
                            data-target="#logoutModal">
                            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                            Logout
                        </a>

                    </div>
                    </li>
        
                </ul>
                </nav>
                <!-- End of Topbar -->   

                <!-- Begin Page Content -->
        <div class="container-fluid">

            <!-- Page Heading -->
            <h1 class="h3 mb-2 text-gray-800">
                {%block pageTitle%} {% endblock %}
            </h1>

            <p class="mb-4"></p>

            <!-- DataTales Example -->
            <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">
                    {% block sectiontitle %} {% endblock %}
                </h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    {% block content %} {% endblock %}
                </div>
            </div>
            </div>

        </div>
        <!-- /.container-fluid -->


            
        
            </div>
            <!-- End of Main Content -->
        
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>Copyright &copy; Your Website 2019</span>
                </div>
                </div>
            </footer>
            <!-- End of Footer -->
    
        </div>
        <!-- End of Content Wrapper -->
        
        </div>
        <!-- End of Page Wrapper -->
    
            
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fas fa-angle-up"></i>
        </a>
            
        <!-- Logout Modal-->
        <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="{{ url_for('login.logout') }}">
                    Logout
                </a>
                </div>
            </div>
            </div>
        </div>
    {% else %}
        {% block login %} {% endblock %}
    {% endif %}
   


  <!-- Bootstrap core JavaScript-->
  <script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  <!-- Core plugin JavaScript-->
  <script src="{{ url_for('static', filename='vendor/jquery-easing/jquery.easing.min.js') }}"></script>
  <!-- Custom scripts for all pages-->
  <script src="{{ url_for('static', filename='js/sb-admin-2.min.js') }}"></script>

</body>
</html>

project/templates/sidebar.html
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
              
        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
          <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
          </div>
          <div class="sidebar-brand-text mx-3">Flask<sup></sup></div>
        </a>
  
        <!-- Divider -->
        <hr class="sidebar-divider my-0">
  
        <!-- Nav Item - Dashboard -->
        <li class="nav-item active">
          <a class="nav-link" href="index.html">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
        </li>
  
        <!-- Divider -->
        <hr class="sidebar-divider">
  
        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
          <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-user"></i>
            <span>User</span>
          </a>
          <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
              <h6 class="collapse-header">User Section</h6>
              <a class="collapse-item" href="{{ url_for('users.addnewuser') }}">Add</a>
              <a class="collapse-item" href="{{ url_for('users.index') }}">List</a>
            </div>
          </div>
        </li>
  
  
        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">
  
        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
          <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>
  
      </ul>
      <!-- End of Sidebar -->